name: jordifornies
favicon: null
layout_spectrum: 0.2883
typography_spectrum: 0.9202364312950522
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#717171'
    - '#414141'
    - '#a2a2a2'
    - '#1c1c1c'
    - '#e0dbd5'
  brandStrength: 0.4605650883167982
  lightness: 0.9969204363878816
  saturation: 0.8059911022428423
  rhythmicContrast: 0.03267081896774471
purpose: []
